### ISSUE TITLE
CodeHarbour: Import exercise (meta data only) as ProFormA-XML via POST endpoint

### ISSUE THREAD

**Issue by leoselig** [leoselig/codeocean#1]
This is the counterpart to https://github.com/openHPI/codeharbor/issues/4

Goal:
- [ ] dedicated controller action for POST located at `/codeharbour` (open for discussion)
- [ ] consumes request body containing an XML according to [ProFormA specification](https://eleed.campussource.de/archive/11/4138)
- [ ] imports meta data (title, description) and sets up dummy relations to any other models just to pass validations for now (should be execution environment only)

**Comment by leoselig** [comment]
Changed description to use [ProFormA specification](https://eleed.campussource.de/archive/11/4138) instead of Thin CC (discussion result)
